# Alembic configuration file.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# leave blank for localtime
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command
# revision_environment = false

# set to 'true' to allow .hierarchyconfig files to load migration hierarchies
# hierarchy_config_by_script_location = false

# set to 'true' to search the source directory for versions outside the script_location
# version_path_separator = os

# set to 'true' to enable logging of the SQL revisions recorded during autogenerate
# show_sqlalchemy_urls = false

# set to 'true' to write warnings and errors to the log instead of stderr
# write_stdin = false

# set to 'true' to render the "tips" command using the version script's module loadable at runtime
# version_script_tips = false

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
